document.write("<div class=\"mdl-layout mdl-js-layout mdl-layout--fixed-header\">");
document.write("  <header class=\"mdl-layout__header\">");
document.write("    <div class=\"mdl-layout__header-row\">");
document.write("      <!-- Title -->");
document.write("      <span class=\"mdl-layout-title\" style=\"font-family: 'Special Elite', cursive;\"><a href=\"..\/home\/index.html\" style=\"text-decoration: none; color: white;\">Magneto Tech<\/a><\/span>");
document.write("      <!-- Add spacer, to align navigation to the right -->");
document.write("      <div class=\"mdl-layout-spacer\"><\/div>");
document.write("      <!-- Navigation. We hide it in small screens. -->");
document.write("      <nav class=\"mdl-navigation mdl-layout--large-screen-only\">");
document.write("        <a class=\"mdl-navigation__link\" href=\"..\/articles\/index.html\">Articles<\/a>");
document.write("        <a class=\"mdl-navigation__link\" href=\"..\/about\/index.html\">About<\/a>");
document.write("      <a class=\"mdl-navigation__link\" href=\"..\/Donate\/index.html\">Donate<\/a>");
document.write("      <\/nav>");
document.write("    <\/div>");
document.write("  <\/header>");
document.write("  <div class=\"mdl-layout__drawer\">");
document.write("      <span class=\"mdl-layout-title\" style=\"font-family: 'Special Elite', cursive;\"><a href=\"..\/home\/index.html\" style=\"text-decoration: none; color: black;\">Magneto Tech<\/a><\/span>");
document.write("    <nav class=\"mdl-navigation\">");
document.write("      <a class=\"mdl-navigation__link\" href=\"..\/articles\/index.html\">Articles<\/a>");
document.write("      <a class=\"mdl-navigation__link\" href=\"..\/about\/index.html\">About<\/a>");
document.write("      <a class=\"mdl-navigation__link\" href=\"..\/donate\/index.html\">Donate<\/a>");
document.write("    <\/nav>");
document.write("  <\/div>");

